// Keyword lists for spam/scam/malicious content detection.
// All matching is done via simple, case-insensitive substring checks.

export const GAMBLING_KEYWORDS = [
  "casino",
  "casinos",
  "slot",
  "slots",
  "slotmachine",
  "slotmachines",
  "pokies",
  "pokie",
  "poker",
  "blackjack",
  "roulette",
  "baccarat",
  "craps",
  "keno",
  "bingo",
  "sportsbook",
  "bets",
  "betting",
  "wager",
  "odds",
  "parlay",
  "accumulator",
  "jackpot",
  "progressive",
  "bonus",
  "bonuscode",
  "welcome-bonus",
  "welcomebonus",
  "deposits",
  "playnow",
  "play-now",
  "realmoney",
  "real-money",
  "live-casino",
  "vip-bonus",
  "highroller",
  "free-roll",
  "freeroll",
  "tournament"
];

export const ADULT_KEYWORDS = [
  "adult",
  "adult-site",
  "porn",
  "porno",
  "pornhub",
  "xvideos",
  "xhamster",
  "xxx",
  "erotic",
  "nude",
  "nudity",
  "cam",
  "camgirl",
  "camgirls",
  "camshow",
  "webcam",
  "livejasmin",
  "chaturbate",
  "escort",
  "escorts",
  "hookup",
  "hookups",
  "milf",
  "fetish",
  "bdsm",
  "pornstar",
  "porn-star",
  "tube",
  "live-sex",
  "live-sexcam",
  "privatechat",
  "private-chat",
  "18+",
  "agegate",
  "over18",
  "over-18",
  "nsfw"
];

export const FAKE_SOFTWARE_KEYWORDS = [
  "download-now",
  "downloadnow",
  "free-download",
  "freedownload",
  "installer",
  "setup.exe",
  "setup-exe",
  "plugin-update",
  "pluginupdate",
  "codec-pack",
  "codecpack",
  "flash-update",
  "flashupdate",
  "driver-updater",
  "driverupdater",
  "registry-cleaner",
  "registrycleaner",
  "pc-booster",
  "pcbooster",
  "optimizer",
  "pc-optimizer",
  "virus-scan",
  "virusscan",
  "antivirus-free",
  "antivirusfree",
  "crack",
  "keygen",
  "serial-key",
  "serialkey",
  "premium-download",
  "premiumdownload",
  "adblocker",
  "allow-notifications",
  "allownotifications",
  "click-allow",
  "clickallow",
  "update-required",
  "updaterequired"
];

export const GENERIC_SCAM_KEYWORDS = [
  "you-won",
  "youwon",
  "congratulations",
  "claim-now",
  "claimnow",
  "free-gift",
  "freegift",
  "prize",
  "reward",
  "giftcard",
  "gift-card",
  "voucher",
  "luckywinner",
  "lucky-winner",
  "limited-offer",
  "limitedoffer",
  "urgent-offer",
  "urgentoffer",
  "act-now",
  "actnow",
  "continue-to",
  "continueto",
  "continue-playing",
  "continueplaying",
  "push-notifications",
  "pushnotifications",
  "notification-alert",
  "survey-reward",
  "exclusive-offer",

  // Deal / offer language
  "great-deal",
  "greatdeal",
  "best-deal",
  "bestdeal",
  "good-deal",
  "gooddeal",
  "hot-deal",
  "hotdeal",
  "special-deal",
  "specialdeal",
  "amazing-deal",
  "amazingdeal"
];

export const AGE_CONSENT_KEYWORDS = [
  "agecheck",
  "age-check",
  "verify-age",
  "verifyage",
  "consent",
  "verify-now",
  "verifynow",
  "signup",
  "sign-up",
  "register",
  "join-now",
  "joinnow",
  "subscribe-now",
  "subscribenow",
  "token",
  "tip",
  "private-room",
  "privateroom",
  "consent-required",
  "age-verification",

  // Explicit age-gate phrases commonly used on adult / scam landers
  "are you 18",
  "are you 18 years old",
  "confirm your age"
];

export const ALL_SPAM_KEYWORDS = [
  ...GAMBLING_KEYWORDS,
  ...ADULT_KEYWORDS,
  ...FAKE_SOFTWARE_KEYWORDS,
  ...GENERIC_SCAM_KEYWORDS,
  ...AGE_CONSENT_KEYWORDS
];


